//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelToDbf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class LastLaunch : global::System.Configuration.ApplicationSettingsBase {
        
        private static LastLaunch defaultInstance = ((LastLaunch)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LastLaunch())));
        
        public static LastLaunch Default {
            get {
                return defaultInstance;
            }
        }
    }
}
